// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolManagement.Infrastructure.Context;

#nullable disable

namespace SchoolManagement.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260225153830_studtable")]
    partial class studtable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SchoolManagement.Domain.Entities.Area", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AreaNm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AreaNm_E")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Resp")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Areas");
                });

            modelBuilder.Entity("SchoolManagement.Domain.Entities.Bank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BankName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankNameEn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Responsible")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Banks");
                });

            modelBuilder.Entity("SchoolManagement.Domain.Entities.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BRNNM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BRNNM_E")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RESP")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Branches");
                });

            modelBuilder.Entity("SchoolManagement.Domain.Entities.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClassNm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClassNmEn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GradeId")
                        .HasColumnType("int");

                    b.Property<int?>("GradesId")
                        .HasColumnType("int");

                    b.Property<int?>("NewGradeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GradesId");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("SchoolManagement.Domain.Entities.CostCenter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CostNm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CostNme")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CostCenters");
                });

            modelBuilder.Entity("SchoolManagement.Domain.Entities.Discount", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<string>("DescountNm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescountNm_E")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("DiscPer")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DiscVal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("DiscVal2")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Discounts");
                });

            modelBuilder.Entity("SchoolManagement.Domain.Entities.Drive", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DrvNm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DrvNmEn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LicEnd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobil")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Drives");
                });

            modelBuilder.Entity("SchoolManagement.Domain.Entities.Grades", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("BookFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("CostCenterId")
                        .HasColumnType("int");

                    b.Property<string>("GradesNm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GradesNm_E")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsExit")
                        .HasColumnType("bit");

                    b.Property<int?>("NextGradeId")
                        .HasColumnType("int");

                    b.Property<int?>("NextSchoolId")
                        .HasColumnType("int");

                    b.Property<int?>("NextStageId")
                        .HasColumnType("int");

                    b.Property<decimal?>("OtherFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PromotionType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("RegistrationFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("SchoolId")
                        .HasColumnType("int");

                    b.Property<int?>("StagesId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Term1Fee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Term2Fee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("TransCostId")
                        .HasColumnType("int");

                    b.Property<decimal?>("TransportFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("studStatusId")
                        .HasColumnType("int");

                    b.Property<int?>("studentStatusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CostCenterId");

                    b.HasIndex("SchoolId");

                    b.HasIndex("StagesId");

                    b.HasIndex("TransCostId");

                    b.HasIndex("studentStatusId");

                    b.ToTable("Grades");
                });

            modelBuilder.Entity("SchoolManagement.Domain.Entities.Nation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NationNm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NationNmE")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Nations");
                });

            modelBuilder.Entity("SchoolManagement.Domain.Entities.School", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("SchoolNm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolNmEn")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Schools");
                });

            modelBuilder.Entity("SchoolManagement.Domain.Entities.Section", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("SectionName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SectionNameEn")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sections");
                });

            modelBuilder.Entity("SchoolManagement.Domain.Entities.Stages", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("StageNM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StageNM_E")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Stages");
                });

            modelBuilder.Entity("SchoolManagement.Domain.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AreaId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("BirthPlace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ClassroomId")
                        .HasColumnType("int");

                    b.Property<int?>("ClassroomsId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreditLimit")
                        .HasColumnType("int");

                    b.Property<bool?>("Depart")
                        .HasColumnType("bit");

                    b.Property<int?>("Discounttypeid")
                        .HasColumnType("int");

                    b.Property<int?>("DiscounttypesId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnglishName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EnrollmentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GradesId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("GraduateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("IdEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("IdIssueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdPlace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImgName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsGraduate")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsNewYear")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobile1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobile2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NationalId")
                        .HasColumnType("int");

                    b.Property<int?>("NationsId")
                        .HasColumnType("int");

                    b.Property<int?>("NextGrade")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Passport")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreviousSchool")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Respons")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SchoolId")
                        .HasColumnType("int");

                    b.Property<int?>("SectionId")
                        .HasColumnType("int");

                    b.Property<int?>("StagesId")
                        .HasColumnType("int");

                    b.Property<bool>("StopAutoPromotion")
                        .HasColumnType("bit");

                    b.Property<bool?>("StopSms")
                        .HasColumnType("bit");

                    b.Property<string>("StudentIdNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentSex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StudentStatusId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SuspenDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("SuspendAccount")
                        .HasColumnType("bit");

                    b.Property<string>("TaxStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TransferTypeId")
                        .HasColumnType("int");

                    b.Property<string>("TypeId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("ClassroomsId");

                    b.HasIndex("DiscounttypesId");

                    b.HasIndex("GradesId");

                    b.HasIndex("NationsId");

                    b.HasIndex("SchoolId");

                    b.HasIndex("SectionId");

                    b.HasIndex("StagesId");

                    b.HasIndex("StudentStatusId");

                    b.HasIndex("TransferTypeId");

                    b.HasIndex("VehicleId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("SchoolManagement.Domain.Entities.StudentStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("StatusName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusNameEn")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StudentStatuses");
                });

            modelBuilder.Entity("SchoolManagement.Domain.Entities.StudyYear", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("FromDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<bool>("IsNewYear")
                        .HasColumnType("bit");

                    b.Property<string>("StudyYearsNm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudyYearsNm_E")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ToDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("StudyYears");
                });

            modelBuilder.Entity("SchoolManagement.Domain.Entities.TransCost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("DiscountPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TransCostNm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TranscostnmE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TransportCostValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TransportCostValue2")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("TransCosts");
                });

            modelBuilder.Entity("SchoolManagement.Domain.Entities.TransLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Responsible")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransLineName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransLineNameEn")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TransLines");
                });

            modelBuilder.Entity("SchoolManagement.Domain.Entities.TransferType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Exmount1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Exmount2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Route")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RouteEng")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TransferTypes");
                });

            modelBuilder.Entity("SchoolManagement.Domain.Entities.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CarName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CarNameEn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Chasee")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DriveId")
                        .HasColumnType("int");

                    b.Property<bool>("InStock")
                        .HasColumnType("bit");

                    b.Property<string>("LicEndDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LicIssueDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlateNum")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DriveId");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("SchoolManagement.Domain.Entities.Class", b =>
                {
                    b.HasOne("SchoolManagement.Domain.Entities.Grades", "Grades")
                        .WithMany()
                        .HasForeignKey("GradesId");

                    b.Navigation("Grades");
                });

            modelBuilder.Entity("SchoolManagement.Domain.Entities.Grades", b =>
                {
                    b.HasOne("SchoolManagement.Domain.Entities.CostCenter", "CostCenter")
                        .WithMany()
                        .HasForeignKey("CostCenterId");

                    b.HasOne("SchoolManagement.Domain.Entities.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId");

                    b.HasOne("SchoolManagement.Domain.Entities.Stages", "stages")
                        .WithMany()
                        .HasForeignKey("StagesId");

                    b.HasOne("SchoolManagement.Domain.Entities.TransCost", "TransCost")
                        .WithMany()
                        .HasForeignKey("TransCostId");

                    b.HasOne("SchoolManagement.Domain.Entities.StudentStatus", "studentStatus")
                        .WithMany()
                        .HasForeignKey("studentStatusId");

                    b.Navigation("CostCenter");

                    b.Navigation("School");

                    b.Navigation("TransCost");

                    b.Navigation("stages");

                    b.Navigation("studentStatus");
                });

            modelBuilder.Entity("SchoolManagement.Domain.Entities.Student", b =>
                {
                    b.HasOne("SchoolManagement.Domain.Entities.Area", "Areas")
                        .WithMany()
                        .HasForeignKey("AreaId");

                    b.HasOne("SchoolManagement.Domain.Entities.Class", "Classrooms")
                        .WithMany()
                        .HasForeignKey("ClassroomsId");

                    b.HasOne("SchoolManagement.Domain.Entities.Discount", "Discounttypes")
                        .WithMany()
                        .HasForeignKey("DiscounttypesId");

                    b.HasOne("SchoolManagement.Domain.Entities.Grades", "Grades")
                        .WithMany()
                        .HasForeignKey("GradesId");

                    b.HasOne("SchoolManagement.Domain.Entities.Nation", "Nations")
                        .WithMany()
                        .HasForeignKey("NationsId");

                    b.HasOne("SchoolManagement.Domain.Entities.School", "Schools")
                        .WithMany()
                        .HasForeignKey("SchoolId");

                    b.HasOne("SchoolManagement.Domain.Entities.Section", "section")
                        .WithMany()
                        .HasForeignKey("SectionId");

                    b.HasOne("SchoolManagement.Domain.Entities.Stages", "stages")
                        .WithMany()
                        .HasForeignKey("StagesId");

                    b.HasOne("SchoolManagement.Domain.Entities.StudentStatus", "StudentStatuses")
                        .WithMany()
                        .HasForeignKey("StudentStatusId");

                    b.HasOne("SchoolManagement.Domain.Entities.TransferType", "TransferTypes")
                        .WithMany()
                        .HasForeignKey("TransferTypeId");

                    b.HasOne("SchoolManagement.Domain.Entities.Vehicle", "Vehicles")
                        .WithMany()
                        .HasForeignKey("VehicleId");

                    b.Navigation("Areas");

                    b.Navigation("Classrooms");

                    b.Navigation("Discounttypes");

                    b.Navigation("Grades");

                    b.Navigation("Nations");

                    b.Navigation("Schools");

                    b.Navigation("StudentStatuses");

                    b.Navigation("TransferTypes");

                    b.Navigation("Vehicles");

                    b.Navigation("section");

                    b.Navigation("stages");
                });

            modelBuilder.Entity("SchoolManagement.Domain.Entities.Vehicle", b =>
                {
                    b.HasOne("SchoolManagement.Domain.Entities.Drive", "Drive")
                        .WithMany()
                        .HasForeignKey("DriveId");

                    b.Navigation("Drive");
                });
#pragma warning restore 612, 618
        }
    }
}
